DROP DATABASE IF EXISTS Used_car_sale;
CREATE DATABASE Used_car_sale;

USE Used_car_sale;

DROP TABLE IF EXISTS Buyers;
CREATE TABLE Buyers(
	Ssn VARCHAR(9) PRIMARY KEY NOT NULL,
	Fname VARCHAR(20) NOT NULL,
	Minit VARCHAR(1),
	Lname VARCHAR(20) NOT NULL,
	Sex VARCHAR(1) NOT NULL,
	Phone VARCHAR(10) NOT NULL,
	Address VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS Sellers;
CREATE TABLE Sellers(
	Ssn VARCHAR(9) PRIMARY KEY NOT NULL,
	Fname VARCHAR(20) NOT NULL,
	Minit VARCHAR(1),
	Lname VARCHAR(20) NOT NULL,
	Sex VARCHAR(1) NOT NULL,
	Phone VARCHAR(10) NOT NULL,
	Address VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS Dealers;
CREATE TABLE Dealers(
	Id NUMERIC(3) NOT NULL PRIMARY KEY,
	Fname VARCHAR(20) NOT NULL,
	Minit VARCHAR(1),
	Lname VARCHAR(20) NOT NULL,
	Sex VARCHAR(1) NOT NULL,
	Phone VARCHAR(10) NOT NULL,
	Branch_no NUMERIC(3) NOT NULL
);

DROP TABLE IF EXISTS Branch;
CREATE TABLE Branch(
	Bno NUMERIC(3) PRIMARY KEY NOT NULL,
	Address VARCHAR(50) NOT NULL,
    Mgr_id Numeric(3)
);

DROP TABLE IF EXISTS Cars;
CREATE TABLE Cars(
	Vin VARCHAR(17) PRIMARY KEY NOT NULL,
	Model VARCHAR(20) NOT NULL,
	Make VARCHAR(20) NOT NULL,
	Year INT(4) NOT NULL,
	Mileage INT NOT NULL,
	Rrp DECIMAL(10,2),
    Bno NUMERIC(3) NOT NULL
);

DROP TABLE IF EXISTS Buy;
CREATE TABLE Buy(
	Vin VARCHAR(17) NOT NULL,
    S_ssn VARCHAR(9) NOT NULL,
	In_id INT NOT NULL,
	FOREIGN KEY (Vin) REFERENCES Cars(Vin),
	FOREIGN KEY (S_ssn)  REFERENCES Sellers(Ssn),
	Price_in DECIMAL(10,2),
	Out_date DATE,
	PRIMARY KEY(In_id)
);

DROP TABLE IF EXISTS Sell;
CREATE TABLE Sell(
	Vin VARCHAR(17) NOT NULL,
    B_ssn VARCHAR(9) NOT NULL,
	Out_id INT NOT NULL,
    In_id INT NOT NULL,
	FOREIGN KEY (Vin) REFERENCES Cars(Vin),
	FOREIGN KEY (B_ssn) REFERENCES Buyers(Ssn),
	FOREIGN KEY (In_id) REFERENCES Buy(In_id),
	Price_out DECIMAL(10,2),
	Out_date DATE,
	PRIMARY KEY(Out_id)
);

ALTER TABLE Branch ADD CONSTRAINT Branch_FK1
foreign key (Mgr_id) REFERENCES Dealers(Id);

ALTER TABLE Dealers ADD CONSTRAINT Dealers_FK1
foreign key (Branch_no) REFERENCES Branch(Bno);

ALTER TABLE CARs ADD CONSTRAINT CARSFK1
FOREIGN KEY (Bno) REFERENCES Branch(Bno);
